/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AtendimentoIndexRouteImport } from './routes/atendimento.index'
import { Route as ServicosServicoRouteImport } from './routes/servicos.$servico'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AtendimentoCidadeRouteImport } from './routes/atendimento.$cidade'
import { Route as ServicosServicoCidadeRouteImport } from './routes/servicos.$servico.$cidade'
import { Route as AtendimentoCidadeBairroRouteImport } from './routes/atendimento.$cidade.$bairro'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoIndexRoute = AtendimentoIndexRouteImport.update({
  id: '/atendimento/',
  path: '/atendimento/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosServicoRoute = ServicosServicoRouteImport.update({
  id: '/servicos/$servico',
  path: '/servicos/$servico',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoCidadeRoute = AtendimentoCidadeRouteImport.update({
  id: '/atendimento/$cidade',
  path: '/atendimento/$cidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosServicoCidadeRoute = ServicosServicoCidadeRouteImport.update({
  id: '/$cidade',
  path: '/$cidade',
  getParentRoute: () => ServicosServicoRoute,
} as any)
const AtendimentoCidadeBairroRoute = AtendimentoCidadeBairroRouteImport.update({
  id: '/$bairro',
  path: '/$bairro',
  getParentRoute: () => AtendimentoCidadeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/atendimento/$cidade': typeof AtendimentoCidadeRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/$servico': typeof ServicosServicoRouteWithChildren
  '/atendimento/': typeof AtendimentoIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/servicos/': typeof ServicosIndexRoute
  '/atendimento/$cidade/$bairro': typeof AtendimentoCidadeBairroRoute
  '/servicos/$servico/$cidade': typeof ServicosServicoCidadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/atendimento/$cidade': typeof AtendimentoCidadeRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/$servico': typeof ServicosServicoRouteWithChildren
  '/atendimento': typeof AtendimentoIndexRoute
  '/blog': typeof BlogIndexRoute
  '/servicos': typeof ServicosIndexRoute
  '/atendimento/$cidade/$bairro': typeof AtendimentoCidadeBairroRoute
  '/servicos/$servico/$cidade': typeof ServicosServicoCidadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/atendimento/$cidade': typeof AtendimentoCidadeRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/$servico': typeof ServicosServicoRouteWithChildren
  '/atendimento/': typeof AtendimentoIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/servicos/': typeof ServicosIndexRoute
  '/atendimento/$cidade/$bairro': typeof AtendimentoCidadeBairroRoute
  '/servicos/$servico/$cidade': typeof ServicosServicoCidadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/sitemap.xml'
    | '/atendimento/$cidade'
    | '/blog/$slug'
    | '/servicos/$servico'
    | '/atendimento/'
    | '/blog/'
    | '/servicos/'
    | '/atendimento/$cidade/$bairro'
    | '/servicos/$servico/$cidade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/sitemap.xml'
    | '/atendimento/$cidade'
    | '/blog/$slug'
    | '/servicos/$servico'
    | '/atendimento'
    | '/blog'
    | '/servicos'
    | '/atendimento/$cidade/$bairro'
    | '/servicos/$servico/$cidade'
  id:
    | '__root__'
    | '/'
    | '/reset-password'
    | '/sitemap.xml'
    | '/atendimento/$cidade'
    | '/blog/$slug'
    | '/servicos/$servico'
    | '/atendimento/'
    | '/blog/'
    | '/servicos/'
    | '/atendimento/$cidade/$bairro'
    | '/servicos/$servico/$cidade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AtendimentoCidadeRoute: typeof AtendimentoCidadeRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  ServicosServicoRoute: typeof ServicosServicoRouteWithChildren
  AtendimentoIndexRoute: typeof AtendimentoIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento/': {
      id: '/atendimento/'
      path: '/atendimento'
      fullPath: '/atendimento/'
      preLoaderRoute: typeof AtendimentoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$servico': {
      id: '/servicos/$servico'
      path: '/servicos/$servico'
      fullPath: '/servicos/$servico'
      preLoaderRoute: typeof ServicosServicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento/$cidade': {
      id: '/atendimento/$cidade'
      path: '/atendimento/$cidade'
      fullPath: '/atendimento/$cidade'
      preLoaderRoute: typeof AtendimentoCidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$servico/$cidade': {
      id: '/servicos/$servico/$cidade'
      path: '/$cidade'
      fullPath: '/servicos/$servico/$cidade'
      preLoaderRoute: typeof ServicosServicoCidadeRouteImport
      parentRoute: typeof ServicosServicoRoute
    }
    '/atendimento/$cidade/$bairro': {
      id: '/atendimento/$cidade/$bairro'
      path: '/$bairro'
      fullPath: '/atendimento/$cidade/$bairro'
      preLoaderRoute: typeof AtendimentoCidadeBairroRouteImport
      parentRoute: typeof AtendimentoCidadeRoute
    }
  }
}

interface AtendimentoCidadeRouteChildren {
  AtendimentoCidadeBairroRoute: typeof AtendimentoCidadeBairroRoute
}

const AtendimentoCidadeRouteChildren: AtendimentoCidadeRouteChildren = {
  AtendimentoCidadeBairroRoute: AtendimentoCidadeBairroRoute,
}

const AtendimentoCidadeRouteWithChildren =
  AtendimentoCidadeRoute._addFileChildren(AtendimentoCidadeRouteChildren)

interface ServicosServicoRouteChildren {
  ServicosServicoCidadeRoute: typeof ServicosServicoCidadeRoute
}

const ServicosServicoRouteChildren: ServicosServicoRouteChildren = {
  ServicosServicoCidadeRoute: ServicosServicoCidadeRoute,
}

const ServicosServicoRouteWithChildren = ServicosServicoRoute._addFileChildren(
  ServicosServicoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AtendimentoCidadeRoute: AtendimentoCidadeRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  ServicosServicoRoute: ServicosServicoRouteWithChildren,
  AtendimentoIndexRoute: AtendimentoIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicosIndexRoute: ServicosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
