/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtendimentoIndexRouteImport } from './routes/atendimento.index'
import { Route as AtendimentoCidadeRouteImport } from './routes/atendimento.$cidade'
import { Route as AtendimentoCidadeBairroRouteImport } from './routes/atendimento.$cidade.$bairro'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoIndexRoute = AtendimentoIndexRouteImport.update({
  id: '/atendimento/',
  path: '/atendimento/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoCidadeRoute = AtendimentoCidadeRouteImport.update({
  id: '/atendimento/$cidade',
  path: '/atendimento/$cidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoCidadeBairroRoute = AtendimentoCidadeBairroRouteImport.update({
  id: '/$bairro',
  path: '/$bairro',
  getParentRoute: () => AtendimentoCidadeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/atendimento/$cidade': typeof AtendimentoCidadeRouteWithChildren
  '/atendimento/': typeof AtendimentoIndexRoute
  '/atendimento/$cidade/$bairro': typeof AtendimentoCidadeBairroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/atendimento/$cidade': typeof AtendimentoCidadeRouteWithChildren
  '/atendimento': typeof AtendimentoIndexRoute
  '/atendimento/$cidade/$bairro': typeof AtendimentoCidadeBairroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/atendimento/$cidade': typeof AtendimentoCidadeRouteWithChildren
  '/atendimento/': typeof AtendimentoIndexRoute
  '/atendimento/$cidade/$bairro': typeof AtendimentoCidadeBairroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/atendimento/$cidade'
    | '/atendimento/'
    | '/atendimento/$cidade/$bairro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/atendimento/$cidade'
    | '/atendimento'
    | '/atendimento/$cidade/$bairro'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/atendimento/$cidade'
    | '/atendimento/'
    | '/atendimento/$cidade/$bairro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AtendimentoCidadeRoute: typeof AtendimentoCidadeRouteWithChildren
  AtendimentoIndexRoute: typeof AtendimentoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento/': {
      id: '/atendimento/'
      path: '/atendimento'
      fullPath: '/atendimento/'
      preLoaderRoute: typeof AtendimentoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento/$cidade': {
      id: '/atendimento/$cidade'
      path: '/atendimento/$cidade'
      fullPath: '/atendimento/$cidade'
      preLoaderRoute: typeof AtendimentoCidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento/$cidade/$bairro': {
      id: '/atendimento/$cidade/$bairro'
      path: '/$bairro'
      fullPath: '/atendimento/$cidade/$bairro'
      preLoaderRoute: typeof AtendimentoCidadeBairroRouteImport
      parentRoute: typeof AtendimentoCidadeRoute
    }
  }
}

interface AtendimentoCidadeRouteChildren {
  AtendimentoCidadeBairroRoute: typeof AtendimentoCidadeBairroRoute
}

const AtendimentoCidadeRouteChildren: AtendimentoCidadeRouteChildren = {
  AtendimentoCidadeBairroRoute: AtendimentoCidadeBairroRoute,
}

const AtendimentoCidadeRouteWithChildren =
  AtendimentoCidadeRoute._addFileChildren(AtendimentoCidadeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AtendimentoCidadeRoute: AtendimentoCidadeRouteWithChildren,
  AtendimentoIndexRoute: AtendimentoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
